version: '3.8'

services:
  db:
    image: postgres:15
    container_name: stock_dividends_db
    restart: always
    environment:
      POSTGRES_DB: stocks_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./stocksApi
    container_name: stock_dividends_backend
    restart: always
    depends_on:
      - db
    ports:
      - "3001:3001"
    environment:
      DB_NAME: stocks_db
      DB_USER: postgres
      DB_PASSWORD: yourpassword
      DB_HOST: db
      DB_PORT: 5432
      PORT: 3001

volumes:
  pgdata:
    driver: local